spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
